# Generated by Django 3.0 on 2019-12-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='someAttr',
            new_name='user',
        ),
    ]
